spring:
  datasource:
    url: jdbc:mysql://localhost:3306/growing_diary?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: PengZiHao1999.
    hikari:
      max-lifetime: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
